[package]
name = "omnidata"
version = "0.1.0"
edition = "2021"
autotests = false
description = "Collect and retrieve data from various data sources."
license = "MIT"

[lib]
name = "omnidata"

[dependencies]
log = "0.4.21"
rocksdb = "0.22.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
serde = "1.0.200"
serde_derive = "1.0.199"


