
use serde_derive::{Serialize, Deserialize};


#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum RelationshipType {
    Mom,
    Dad,
    Brother,
    Sister,
    Son,
    Daughter,
    Parent,
    Child,
    Wife,
    Husband,
    Spouse,
    Fiance,
    Boyfriend,
    Girlfriend,
    FriendsWithBenefits,
    Escort,
    Aunt,
    GrandFather,
    Grandmother,
    Nephew,
    Neice,
    StepFather,
    StepMother,
    StepParent,
    FosterFather,
    FosterMother,
    FosterSon,
    FosterDaughter,
    FosterParent,
    FosterChild,
    GodFather,
    GodMother,
    GodParent,
    GodSon,
    GodDaughter,
    GodChild,
    Uncle,
    Cousin,
    FamilyFriend,
    LongTimeFriend,
    NewFriend,
    Friend,
    Aquaintance,
    PetDog,
    PetCat,
    PetOther,
    Enemy,
    Boss,
    Manager,
    BusinessOwner,
    CoWorker,
    Employee,
    Contractor,
    SubContractor,
    ServiceProvider,
    Doctor,
    Nurse,
    Therapist,
    Lawyer,
    Accountant,
    InsuranceBroker,
    Banker,
    InvestmentManager,
    FinancialAdvisor,
    Teacher,
    Student,
    Classmate,
    SecurityGuard,
    LocallyElectedOfficial,
    MilitaryHigherRank,
    MilitaryLowerRank,
    Mentor,
    Advisor,
    Neighbor,
    Guardian,
    ProbationOfficer,
    ParoleOfficer,
    Landlord,
    Tenant,
    Teammate
}



